config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' =>'devise/sessions#destroy'
  end   
  resources :friend_lists
  resources :friends
  #get 'home/index'
  root 'friend_lists#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to:user  
end

app/models/friend_list.rb
class FriendList < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many:friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friend_lists_controller.rb
class FriendListsController < ApplicationController
  before_action :set_friend_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friend_lists or /friend_lists.json
  def index
    @friend_lists = FriendList.all
  end

  # GET /friend_lists/1 or /friend_lists/1.json
  def show
  end

  # GET /friend_lists/new
  def new
    @friend_list = FriendList.new
    #@friend_list = current_user.friends.build
  end

  # GET /friend_lists/1/edit
  def edit
  end

  # POST /friend_lists or /friend_lists.json
  def create
    @friend_list = FriendList.new(friend_list_params)
    #@friend_list = current_user.friends.build (friend_list_params)

    respond_to do |format|
      if @friend_list.save
        format.html { redirect_to friend_list_url(@friend_list), notice: "Friend list was successfully created." }
        format.json { render :show, status: :created, location: @friend_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friend_lists/1 or /friend_lists/1.json
  def update
    respond_to do |format|
      if @friend_list.update(friend_list_params)
        format.html { redirect_to friend_list_url(@friend_list), notice: "Friend list was successfully updated." }
        format.json { render :show, status: :ok, location: @friend_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friend_lists/1 or /friend_lists/1.json
  def destroy
    @friend_list.destroy

    respond_to do |format|
      format.html { redirect_to friend_lists_url, notice: "Friend list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend_list = current_user.friends.find_by(id: params[:id])
    redirect_to friend_lists_path, notice: "not authorized to edit this friend" if @friend_list.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend_list
      @friend_list = FriendList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_list_params
      params.require(:friend_list).permit(:first_name, :last_name, :email, :phone, :insta, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_lists_helper.rb
module FriendListsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friend_lists/_form.html.erb
<%= form_with(model: friend_list) do |form| %>
  <% if friend_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend_list.errors.count, "error") %> prohibited this friend_list from being saved:</h2>

      <ul>
        <% friend_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name ,class:"form-control", placeholder:"First Name" %>
  </div>
<br>
  <div>
    <% form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name ,class:"form-control", placeholder:"Last Name" %>
  </div>
<br>
  <div>
    <% form.label :email, style: "display: block" %>
    <%= form.text_field :email ,class:"form-control", placeholder:"Email" %>
  </div>
<br>
  <div>
    <% form.label :phone, style: "display: block" %>
    <%= form.text_field :phone ,class:"form-control", placeholder:"Phone Number" %>
  </div>
<br>
  <div>
    <% form.label :insta, style: "display: block" %>
    <%= form.text_field :insta ,class:"form-control", placeholder:"Instagram" %>
  </div>
<br>
  <div>
    <% form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id,id: :friend_lists_user_id,class:"form-control", value:current_user.id %>
  </div>

<br>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_lists/_friend_list.html.erb
<div id="<%= dom_id friend_list %>">
  <table class="table table-hover table-bordered">
  <thead class="thead-dark">
<!--<tr>
  <p><th>
    <strong>First name</strong>
    
  </p></th>

  <p><th>
    <strong>Last name</strong>
  
  </p></th>

  <p><th>
    <strong>Email</strong>
    
  </p></th>

  <p><th>
    <strong>Phone</strong>
    
  </p></th>

  <p><th>
    <strong>Insta</strong>
    
  </p></th>
  <p><th>
    <strong></strong>
  </p></th>

  </tr>-->
  <tbody>
    <tr>
      <td><%= friend_list.first_name %></td>
      <td><%= friend_list.last_name %></td>
      <td><%= friend_list.email %></td>
      <td><%= friend_list.phone %></td>
      <td><%= friend_list.insta %></td>
      <td><%= friend_list.user_id %></td>
      <td><%= link_to "Show", friend_list %></td>
    </tr>
    

  </tbody>
  </table>

</div>

app/views/friend_lists/edit.html.erb
<h1>Editing friend list</h1>

<%= render 'form' , friend_list: @friend_list %>

<br>

<div>
  <%= link_to "Show this friend list", @friend_list , class:"btn btn-secondary btn-sm" %> |
  <%= link_to "Back to friend lists", friend_lists_path , class:"btn btn-warning btn-sm" %>
</div>

app/views/friend_lists/index.html.erb
<p style="color: green"></p>
<%if user_signed_in?%>
<h1>Friend list</h1>

<div id="friend_lists">
  <table class="table table-hover table-bordered">
    <thead class="thead-dark">
<tr>
  <p><th>
    <strong>First name</strong>
    
  </p></th>

  <p><th>
    <strong>Last name</strong>
  
  </p></th>

  <p><th>
    <strong>Email</strong>
    
  </p></th>

  <p><th>
    <strong>Phone</strong>
    
  </p></th>

  <p><th>
    <strong>Insta</strong>
    
  </p></th>
  <p><th>
    <strong></strong>
  </p></th>
  <p> <th> 
    <strong>User Id</strong> 
  </th> </p>

  </tr>
<tbody>
  <% @friend_lists.each do |friend_list| %>
  <tr>
      <td><%= friend_list.first_name %></td>
      <td><%= friend_list.last_name %></td>
      <td><%= friend_list.email %></td>
      <td><%= friend_list.phone %></td>
      <td><%= friend_list.insta %></td>
      <td><%= link_to "Show", friend_list %></td>
      <td><%= friend_list.user_id %></td>
    </tr>
    

    
   
    <% render friend_list %>
    
    <% end %>
</tbody>
</table>

</div>

<!--<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>-->

<%= link_to "New friend list", new_friend_list_path, class:"btn btn-secondary btn-sm" %>
<% else %>
<h1>HELLO WORLD!</h1>
<h2>this is my first rails webpage</h2>
<% end %>

app/views/friend_lists/new.html.erb
<h1>Add New Friend</h1>

<br>

<%= render "form", friend_list: @friend_list %>

<br>

<div>
  <%= link_to "Back to friend lists", friend_lists_path, class:"btn btn-warning btn-sm" %>
</div>

app/views/friend_lists/show.html.erb
<p style="color: green"></p>





<div class="jumbotron">
  <h1 class="display-4"><%= @friend_list.first_name%> <%= @friend_list.last_name %></h1>
  <p class="lead">
      <%= @friend_list.email %> |
      <%= @friend_list.phone %> |
      <%= @friend_list.insta %> |

  </p>
  <hr class="my-4">
  <p></p>
  <a 
  
   <% if user_signed_in? %>
  <%= link_to "Edit this friend list", edit_friend_list_path(@friend_list), class:"btn btn-info btn-sm " %> <% end %> |
  <%= link_to "Back to friend lists", friend_lists_path, class:"btn btn-warning btn-sm" %>

  <br>
  <br>
  <% if user_signed_in? %>
  <%= button_to "Destroy this friend list",  @friend_list, method: :delete, class:"btn btn-danger" %>
  <% end %>
</a>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friends', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "FriendList", friend_lists_path, class:"nav-link" %>
      </li>

      <% if user_signed_in? %>

      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path,:method=>:delete ,class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Add Friend", new_friend_list_path, class:"nav-link" %>
      </li>

      
      <% else %>

      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>

      <% end %>
      
      <li class="nav-item">
        <%= link_to "AboutUs", home_about_path, class:"nav-link" %>
      </li>
      <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>-->
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1><ul> About Us </ul></h1>
<h2>A ruby on rails project by Naman Raj <br> Contact: +919102315422</h2>

app/views/home/index.html.erb
<h1>HELLO WORLD!</h1>
<h2>this is my first rails webpage</h2>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>friends app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>  
       <%= yield %>
     </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>